<?php

$chunk = $modx->newObject('modChunk');
$chunk->fromArray(array(
    'name' => 'tplContactEmail'
    ,'description' => 'The template for the email generated by the Contact Us form.'
    ,'snippet' => include(dirname(__FILE__).'/content/tplcontactemail.content.php')
));

return $chunk;

?>
